save_path: "/20A021/ccomhuqin_seg/save_path/finetune0828/"
nproc: 1
devices: 0,1,2,3
arch: "frameatst"
test_from_checkpoint: "/20A021/ccomhuqin_seg/save_path/finetune0828/last.ckpt" # This value means only test mode, NO TRAINING!!!!!
pretrained_ckpt_path: "/20A021/dataset_from_dyl/save_path/pretrainSmall0809/last.ckpt"
learning_rate: 0.05 # Considering the large data size of strongly-labeled AudioSet, we only search over 3 different learning rates for each model, i.e. 0.05, 0.1 and 0.5.
lr_scale: 0.75
batch_size_per_gpu: 64
max_epochs: 200
dcase_conf: "/20A021/projects/audiossl/audiossl/methods/atstframe/downstream/utils_as_strong/conf/frame_40.yaml"
dataset_name: "ccomhuqin_as_strong" # 在datasets/init.py register新的dataset，因为num_label需要修改
freeze_mode: False
num_workers: 4