training:
  batch_size: [128, 128]
  median_window: 7
  n_test_thresholds: 50
  weak_split: 0.9
  batch_len_index: 1
  seed: 42
  val_thresholds: [0.5]
data:
  synth_train_num: 10000
  synth_folder: "/YOUR_OWN_PATH/DCASE/dcase2021/dataset/audio/train/synthetic21_train/soundscapes_16k/"
  synth_folder_44k: "/YOUR_OWN_PATH/DCASE/dcase2021/dataset/audio/train/synthetic21_train/soundscapes/"
  synth_tsv:  "/YOUR_OWN_PATH/DCASE/dcase2021/dataset/metadata/train/synthetic21_train/soundscapes.tsv"
  weak_folder: "/YOUR_OWN_PATH/DCASE/dcase2021/dataset/audio/train/weak_16k/"
  weak_folder_44k: "/YOUR_OWN_PATH/DCASE/dcase2021/dataset/audio/train/weak/"
  weak_tsv: "/YOUR_OWN_PATH/DCASE/dcase2021/dataset/metadata/train/weak.tsv"
  unlabeled_folder: "/YOUR_OWN_PATH/DCASE/dcase2021/dataset/audio/train/unlabel_in_domain_16k/"
  unlabeled_folder_44k: "/YOUR_OWN_PATH/DCASE/dcase2021/dataset/audio/train/unlabel_in_domain/"
  synth_val_folder: "/YOUR_OWN_PATH/DCASE/dcase2021/dataset/audio/validation/synthetic21_validation/soundscapes_16k/"
  synth_val_folder_44k: "/YOUR_OWN_PATH/DCASE/dcase2021/dataset/audio/validation/synthetic21_validation/soundscapes/"
  synth_val_tsv:  "/YOUR_OWN_PATH/DCASE/dcase2021/dataset/metadata/validation/synthetic21_validation/soundscapes.tsv"
  synth_val_dur: "/YOUR_OWN_PATH/DCASE/dcase2021/dataset/metadata/validation/synthetic21_validation/durations.tsv"
  test_folder: "/YOUR_OWN_PATH/DCASE/dcase2021/dataset/audio/validation/validation_16k/"
  test_folder_44k: "/YOUR_OWN_PATH/DCASE/dcase2021/dataset/audio/validation/validation/"
  test_tsv: "/YOUR_OWN_PATH/DCASE/dcase2021/dataset/metadata/validation/validation.tsv"
  test_dur: "/YOUR_OWN_PATH/DCASE/dcase2021/dataset/metadata/validation/validation_durations.tsv"
  eval_folder: "/YOUR_OWN_PATH/DCASE/dcase2021/dataset/audio/eval21_16k"
  eval_folder_44k: "/YOUR_OWN_PATH/DCASE/dcase2021/dataset/audio/eval21"
  audio_max_len: 10
  fs: 16000
  net_subsample: 16
feats:
  n_mels: 128
  n_filters: 400
  hop_length: 160
  n_window: 400
  sample_rate: 16000
  f_min: 0
  f_max: 8000

